name: nutritrack
description: A nutrition tracking app for Semester 4 project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date/Time handling
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.6

  # HTTP communication with ESP32 Wi-Fi scale
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
